services:
  httpfs:
    build: .
    container_name: httpfs
    volumes:
      - ./static:/var/www/static
      - ./images:/var/www/images
      - ./icons:/var/www/icons
      - ./videos:/var/www/videos
      - ./audio:/var/www/audio
    restart: unless-stopped
    ports:
      - 8080:8080