services:
  httpfs:
    build: .
    container_name: httpfs
    volumes:
      - ./static:/var/www/static
      - ./images:/var/www/images #optional
      - ./icons:/var/www/icons #optional
      - ./videos:/var/www/videos #optional
      - ./audio:/var/www/audio #optional
    restart: unless-stopped
    ports:
      - 8080:8080